import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { Bot, CalendarClock, CheckCircle2, ChevronRight, CircleDollarSign, Edit3, Loader2, Mail, MessageCircle, PhoneCall, Plus, Send, Trash2, Users, X, XCircle } from "lucide-react";
import { toast } from "sonner";
import { AdminShell } from "@/components/admin-shell";
import { deleteCrmLead, deleteCrmMarketing, getCrmWorkspace, saveCrmLead, saveCrmMarketing, sendCrmCommunication } from "@/lib/crm.functions";

export const Route = createFileRoute("/_authenticated/admin/crm")({ component: CrmPage });
const stages = ["new", "contacted", "qualified", "proposal", "won", "lost"];

function CrmPage() {
  const load = useServerFn(getCrmWorkspace);
  const saveLead = useServerFn(saveCrmLead);
  const removeLead = useServerFn(deleteCrmLead);
  const saveMarketing = useServerFn(saveCrmMarketing);
  const removeMarketing = useServerFn(deleteCrmMarketing);
  const sendMessage = useServerFn(sendCrmCommunication);
  const qc = useQueryClient();
  const [tab, setTab] = useState<"leads" | "campaigns" | "automations" | "integrations">("leads");
  const [leadEditor, setLeadEditor] = useState<any>(null);
  const [marketingEditor, setMarketingEditor] = useState<any>(null);
  const [composer, setComposer] = useState<any>(null);
  const { data, isLoading } = useQuery<any>({ queryKey: ["crm-workspace"], queryFn: () => load(), refetchInterval: 20000 });
  const refresh = () => qc.invalidateQueries({ queryKey: ["crm-workspace"] });
  const leadSave = useMutation({ mutationFn: (value: any) => saveLead({ data: value }), onSuccess: () => { toast.success("Lead saved"); setLeadEditor(null); refresh(); }, onError: fail });
  const leadDelete = useMutation({ mutationFn: (id: string) => removeLead({ data: { id } }), onSuccess: () => { toast.success("Lead deleted"); refresh(); }, onError: fail });
  const marketingSave = useMutation({ mutationFn: (value: any) => saveMarketing({ data: value }), onSuccess: () => { toast.success("Saved"); setMarketingEditor(null); refresh(); }, onError: fail });
  const marketingDelete = useMutation({ mutationFn: (value: any) => removeMarketing({ data: value }), onSuccess: () => { toast.success("Deleted"); refresh(); }, onError: fail });
  const communication = useMutation({ mutationFn: (value: any) => sendMessage({ data: value }), onSuccess: () => { toast.success("Communication sent"); setComposer(null); refresh(); }, onError: fail });
  const leads = data?.leads || [];
  const pipelineValue = leads.filter((l: any) => !["won","lost"].includes(l.stage)).reduce((sum: number,l: any) => sum+l.value_minor,0);

  return <AdminShell title="CRM & automation">
    <div className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-orange">Sales workspace</p><h1 className="mt-2 text-2xl font-semibold text-brand-navy">CRM & automation</h1><p className="mt-1 text-sm text-muted-foreground">Leads, pipeline, WhatsApp, IVR calls, email campaigns and follow-up automation.</p></div>{tab === "leads" && <button onClick={() => setLeadEditor({})} className="crm-primary"><Plus className="h-4 w-4" /> Add lead</button>}{tab === "campaigns" && <button onClick={() => setMarketingEditor({kind:"campaign"})} className="crm-primary"><Plus className="h-4 w-4" /> New campaign</button>}{tab === "automations" && <button onClick={() => setMarketingEditor({kind:"automation"})} className="crm-primary"><Plus className="h-4 w-4" /> New automation</button>}</div>
    <div className="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Total leads" value={leads.length}/><Metric icon={CircleDollarSign} label="Open pipeline" value={money(pipelineValue)}/><Metric icon={CalendarClock} label="Follow-ups" value={leads.filter((l:any)=>l.next_followup_at).length}/><Metric icon={Send} label="Communications" value={data?.logs?.length || 0}/></div>
    <div className="mb-5 flex gap-1 overflow-x-auto rounded-xl border bg-background p-1">{(["leads","campaigns","automations","integrations"] as const).map((name)=><button key={name} onClick={()=>setTab(name)} className={`rounded-lg px-4 py-2 text-xs font-semibold capitalize ${tab===name?"bg-brand-navy text-white":"text-muted-foreground hover:bg-muted"}`}>{name}</button>)}</div>
    {isLoading ? <div className="grid min-h-80 place-items-center"><Loader2 className="h-6 w-6 animate-spin text-brand-orange"/></div> :
    tab === "leads" ? <LeadPipeline leads={leads} onEdit={setLeadEditor} onDelete={(id)=>confirm("Delete this lead and its history?")&&leadDelete.mutate(id)} onContact={setComposer}/> :
    tab === "campaigns" ? <MarketingList kind="campaign" items={data?.campaigns||[]} onEdit={(v)=>setMarketingEditor({...v,kind:"campaign"})} onDelete={(id)=>marketingDelete.mutate({kind:"campaign",id})}/> :
    tab === "automations" ? <MarketingList kind="automation" items={data?.rules||[]} onEdit={(v)=>setMarketingEditor({...v,kind:"automation"})} onDelete={(id)=>marketingDelete.mutate({kind:"automation",id})}/> :
    <Integrations values={data?.integrations} logs={data?.logs||[]}/>}
    {leadEditor && <LeadModal initial={leadEditor} saving={leadSave.isPending} onClose={()=>setLeadEditor(null)} onSave={(v)=>leadSave.mutate(v)}/>}
    {marketingEditor && <MarketingModal initial={marketingEditor} saving={marketingSave.isPending} onClose={()=>setMarketingEditor(null)} onSave={(v)=>marketingSave.mutate(v)}/>}
    {composer && <ComposeModal lead={composer} saving={communication.isPending} onClose={()=>setComposer(null)} onSend={(v)=>communication.mutate(v)}/>}
    <style>{`.crm-primary{display:inline-flex;align-items:center;gap:.4rem;border-radius:.5rem;background:hsl(var(--brand-navy));padding:.65rem 1rem;font-size:.8rem;font-weight:600;color:white}.crm-input{width:100%;border:1px solid hsl(var(--border));border-radius:.45rem;background:hsl(var(--background));padding:.6rem .75rem;font-size:.85rem;outline:none}.crm-input:focus{box-shadow:0 0 0 2px oklch(.72 .17 55/.35);border-color:transparent}`}</style>
  </AdminShell>;
}

function LeadPipeline({leads,onEdit,onDelete,onContact}:any){return <div className="grid gap-4 xl:grid-cols-3 2xl:grid-cols-6">{stages.map(stage=><section key={stage} className="min-w-0 rounded-xl border bg-muted/20"><div className="flex items-center justify-between border-b px-3 py-3"><h2 className="text-xs font-bold capitalize text-brand-navy">{stage}</h2><span className="rounded-full bg-background px-2 py-0.5 text-[10px]">{leads.filter((l:any)=>l.stage===stage).length}</span></div><div className="space-y-2 p-2">{leads.filter((l:any)=>l.stage===stage).map((lead:any)=><article key={lead.id} className="rounded-lg border bg-background p-3 shadow-sm"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><h3 className="truncate text-xs font-semibold text-brand-navy">{lead.full_name}</h3><p className="truncate text-[11px] text-muted-foreground">{lead.company||lead.email||lead.phone||"No contact"}</p></div><button onClick={()=>onEdit(lead)}><Edit3 className="h-3.5 w-3.5"/></button></div><p className="mt-3 text-xs font-semibold">{money(lead.value_minor)}</p>{lead.next_followup_at&&<p className="mt-1 text-[10px] text-amber-700">Follow up {new Date(lead.next_followup_at).toLocaleDateString()}</p>}<div className="mt-3 flex gap-1"><button onClick={()=>onContact(lead)} className="flex flex-1 items-center justify-center gap-1 rounded-md bg-brand-navy px-2 py-1.5 text-[10px] font-semibold text-white"><Send className="h-3 w-3"/> Contact</button><button onClick={()=>onDelete(lead.id)} className="grid h-7 w-7 place-items-center rounded-md border text-red-600"><Trash2 className="h-3 w-3"/></button></div></article>)}</div></section>)}</div>}
function MarketingList({kind,items,onEdit,onDelete}:any){return <div className="rounded-xl border bg-background">{items.length?<div className="divide-y">{items.map((item:any)=><div key={item.id} className="flex flex-wrap items-center gap-4 p-4"><span className="grid h-10 w-10 place-items-center rounded-lg bg-brand-orange/10 text-brand-navy">{kind==="campaign"?<Send className="h-4 w-4"/>:<Bot className="h-4 w-4"/>}</span><div className="min-w-0 flex-1"><p className="text-sm font-semibold text-brand-navy">{item.name}</p><p className="mt-1 text-xs capitalize text-muted-foreground">{item.channel} · {kind==="campaign"?(item.status||"draft"):`${item.trigger_type} · ${item.delay_minutes} min delay`}</p></div><button onClick={()=>onEdit(item)} className="rounded-md border px-3 py-2 text-xs">Edit</button><button onClick={()=>confirm("Delete this item?")&&onDelete(item.id)} className="grid h-8 w-8 place-items-center rounded-md text-red-600"><Trash2 className="h-4 w-4"/></button></div>)}</div>:<Empty text={`No ${kind}s created yet.`}/>}</div>}
function Integrations({values,logs}:any){return <div className="space-y-6"><div className="grid gap-4 md:grid-cols-3"><Integration icon={MessageCircle} name="WhatsApp Cloud API" active={values?.whatsapp} env="META_WHATSAPP_TOKEN"/><Integration icon={PhoneCall} name="Twilio IVR & calls" active={values?.voice} env="TWILIO_ACCOUNT_SID"/><Integration icon={Mail} name="Resend email marketing" active={values?.email} env="RESEND_API_KEY"/></div><section className="rounded-xl border bg-background"><div className="border-b p-4"><h2 className="font-semibold text-brand-navy">Communication log</h2></div>{logs.length?<div className="divide-y">{logs.map((log:any)=><div key={log.id} className="grid gap-2 p-4 text-xs sm:grid-cols-[110px_1fr_140px_90px]"><span className="capitalize">{log.channel}</span><span className="truncate font-mono">{log.recipient}</span><span>{new Date(log.created_at).toLocaleString("en-IN")}</span><span className={log.status==="sent"?"text-emerald-700":"text-red-600"}>{log.status}</span>{log.error_message&&<p className="text-red-600 sm:col-span-4">{log.error_message}</p>}</div>)}</div>:<Empty text="No communications logged yet."/>}</section></div>}
function Integration({icon:Icon,name,active,env}:any){return <div className="rounded-xl border bg-background p-5"><div className="flex items-start justify-between"><span className="grid h-10 w-10 place-items-center rounded-lg bg-brand-navy/5 text-brand-navy"><Icon className="h-5 w-5"/></span>{active?<span className="inline-flex items-center gap-1 text-xs font-semibold text-emerald-700"><CheckCircle2 className="h-4 w-4"/> Connected</span>:<span className="inline-flex items-center gap-1 text-xs font-semibold text-amber-700"><XCircle className="h-4 w-4"/> Setup needed</span>}</div><h3 className="mt-4 text-sm font-semibold">{name}</h3><p className="mt-1 text-[11px] text-muted-foreground">Configure securely with {env} in the server environment.</p></div>}

function LeadModal({initial,saving,onClose,onSave}:any){const [v,setV]=useState({id:initial.id,full_name:initial.full_name||"",email:initial.email||"",phone:initial.phone||"",company:initial.company||"",stage:initial.stage||"new",source:initial.source||"manual",value_minor:initial.value_minor||0,currency:initial.currency||"INR",tags:initial.tags||[],next_followup_at:initial.next_followup_at?new Date(initial.next_followup_at).toISOString().slice(0,16):"",notes:initial.notes||""});return <Modal title={initial.id?"Edit lead":"Add lead"} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave({...v,next_followup_at:v.next_followup_at?new Date(v.next_followup_at).toISOString():null})}} className="space-y-4"><Grid><Field label="Full name"><input required value={v.full_name} onChange={e=>setV({...v,full_name:e.target.value})} className="crm-input"/></Field><Field label="Company"><input value={v.company} onChange={e=>setV({...v,company:e.target.value})} className="crm-input"/></Field><Field label="Email"><input type="email" value={v.email} onChange={e=>setV({...v,email:e.target.value})} className="crm-input"/></Field><Field label="Phone"><input value={v.phone} onChange={e=>setV({...v,phone:e.target.value})} className="crm-input"/></Field><Field label="Pipeline stage"><select value={v.stage} onChange={e=>setV({...v,stage:e.target.value})} className="crm-input">{stages.map(s=><option key={s}>{s}</option>)}</select></Field><Field label="Source"><input value={v.source} onChange={e=>setV({...v,source:e.target.value})} className="crm-input"/></Field><Field label="Deal value (INR)"><input type="number" min="0" value={v.value_minor/100} onChange={e=>setV({...v,value_minor:Math.round(Number(e.target.value)*100)})} className="crm-input"/></Field><Field label="Next follow-up"><input type="datetime-local" value={v.next_followup_at} onChange={e=>setV({...v,next_followup_at:e.target.value})} className="crm-input"/></Field></Grid><Field label="Tags (comma separated)"><input value={v.tags.join(", ")} onChange={e=>setV({...v,tags:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} className="crm-input"/></Field><Field label="Notes"><textarea rows={4} value={v.notes} onChange={e=>setV({...v,notes:e.target.value})} className="crm-input"/></Field><Actions saving={saving} onClose={onClose}/></form></Modal>}
function MarketingModal({initial,saving,onClose,onSave}:any){const campaign=initial.kind==="campaign";const [v,setV]=useState({...initial,name:initial.name||"",channel:initial.channel||"email",subject:initial.subject||"",template:initial.template||"",status:initial.status||"draft",target_stage:initial.target_stage||"",trigger_type:initial.trigger_type||"lead_created",delay_minutes:initial.delay_minutes||0,is_active:initial.is_active??true,scheduled_at:initial.scheduled_at||""});return <Modal title={`${initial.id?"Edit":"New"} ${campaign?"campaign":"automation"}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSave(v)}} className="space-y-4"><Field label="Name"><input required value={v.name} onChange={e=>setV({...v,name:e.target.value})} className="crm-input"/></Field><Grid><Field label="Channel"><select value={v.channel} onChange={e=>setV({...v,channel:e.target.value})} className="crm-input"><option value="email">Email</option><option value="whatsapp">WhatsApp</option><option value="voice">IVR voice</option></select></Field>{campaign?<Field label="Target stage"><select value={v.target_stage} onChange={e=>setV({...v,target_stage:e.target.value})} className="crm-input"><option value="">All leads</option>{stages.map(s=><option key={s}>{s}</option>)}</select></Field>:<Field label="Trigger"><select value={v.trigger_type} onChange={e=>setV({...v,trigger_type:e.target.value})} className="crm-input"><option value="lead_created">Lead created</option><option value="stage_changed">Stage changed</option><option value="followup_due">Follow-up due</option><option value="payment_received">Payment received</option></select></Field>}</Grid>{v.channel==="email"&&<Field label="Email subject"><input value={v.subject} onChange={e=>setV({...v,subject:e.target.value})} className="crm-input"/></Field>}<Field label="Message template"><textarea required rows={7} value={v.template} onChange={e=>setV({...v,template:e.target.value})} placeholder="Use a personalised message for your audience." className="crm-input"/></Field>{!campaign&&<Field label="Delay in minutes"><input type="number" min="0" value={v.delay_minutes} onChange={e=>setV({...v,delay_minutes:Number(e.target.value)})} className="crm-input"/></Field>}<Actions saving={saving} onClose={onClose}/></form></Modal>}
function ComposeModal({lead,saving,onClose,onSend}:any){const [channel,setChannel]=useState("email");const [subject,setSubject]=useState("");const [content,setContent]=useState(`Hello ${lead.full_name},\n\nThank you for your interest in 100 Web Technologies.`);return <Modal title={`Contact ${lead.full_name}`} onClose={onClose}><form onSubmit={e=>{e.preventDefault();onSend({leadId:lead.id,channel,subject,content})}} className="space-y-4"><Field label="Channel"><select value={channel} onChange={e=>setChannel(e.target.value)} className="crm-input"><option value="email">Email marketing</option><option value="whatsapp">WhatsApp</option><option value="voice">IVR / outbound call</option></select></Field>{channel==="email"&&<Field label="Subject"><input required value={subject} onChange={e=>setSubject(e.target.value)} className="crm-input"/></Field>}<Field label={channel==="voice"?"Call log note":"Message"}><textarea required rows={7} value={content} onChange={e=>setContent(e.target.value)} className="crm-input"/></Field><Actions saving={saving} onClose={onClose} label={channel==="voice"?"Start call":"Send now"}/></form></Modal>}
function Modal({title,onClose,children}:any){return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/45 sm:items-center sm:p-4"><div className="w-full max-w-2xl rounded-t-2xl bg-background shadow-xl sm:rounded-2xl"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-semibold text-brand-navy">{title}</h2><button onClick={onClose}><X className="h-4 w-4"/></button></div><div className="max-h-[78vh] overflow-y-auto p-5">{children}</div></div></div>}
function Actions({saving,onClose,label="Save"}:any){return <div className="flex justify-end gap-2 border-t pt-4"><button type="button" onClick={onClose} className="rounded-md border px-4 py-2 text-xs">Cancel</button><button disabled={saving} className="crm-primary">{saving&&<Loader2 className="h-4 w-4 animate-spin"/>}{label}</button></div>}
function Field({label,children}:any){return <label className="block"><span className="mb-1.5 block text-xs font-medium">{label}</span>{children}</label>}
function Grid({children}:any){return <div className="grid gap-4 sm:grid-cols-2">{children}</div>}
function Metric({icon:Icon,label,value}:any){return <div className="rounded-xl border bg-background p-4"><div className="flex items-center justify-between"><Icon className="h-4 w-4 text-brand-orange"/><span className="text-xl font-semibold text-brand-navy">{value}</span></div><p className="mt-3 text-xs text-muted-foreground">{label}</p></div>}
function Empty({text}:any){return <div className="p-12 text-center text-sm text-muted-foreground">{text}</div>}
function money(value:number){return new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format((value||0)/100)}
function fail(error:Error){toast.error(error.message)}
